version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install npm dependencies
      - npm install

  build:
    commands:
      # Run the build script
      - npm run build

artifacts:
  # Specify files to include in the deployment artifact
  files:
    - '**/*'
